name: "Required Labels"
description: "Notifies on issue if required labels are not added"
inputs:
  labels: # id of input
    description: "Required labels"
    required: true
  GITHUB_TOKEN:
    description: "Github Token"
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "index.js"
