on:
  issues:
    types: [opened]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Required Labels
    steps:
      - name: Required Labels
        uses: muhaddimu/required-labels@master
        with:
          labels: "Hacker"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
